### ISSUE TITLE
it does not get files fron internet

### ISSUE THREAD

**Issue by YashPatel000** [Tech-How/Bing-Wallpaper-for-iOS#1]

**Comment by Tech-How** [comment]
Hi, sorry to hear you're having trouble with it. Could you try these steps for me?

1. Delete the shortcut from the Shortcuts app
2. Open the Files app, and navigate back to the first page. Click on "On my iPhone/iPad"
3. Delete the Bing Wallpaper folder

Now, try re-downloading the shortcut, making sure to press Allow on each permission the first time you run it.
If you're still having trouble, could you visit this link, and copy and paste the output here?

https://bing.com/HPImageArchive.aspx?format=js&idx=0&mkt=ROW&n=1https://bing.com/HPImageArchive.aspx?format=js&idx=0&mkt=ROW&n=1

**Comment by YashPatel000** [comment]
Still shows the request time out.

Here is the link output


{"images":[{"startdate":"20230419","fullstartdate":"202304191830","enddate":"20230420","url":"/th?id=OHR.BeltedGalloway_EN-IN4523698216_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp","urlbase":"/th?id=OHR.BeltedGalloway_EN-IN4523698216","copyright":"Belted Galloway cows in Scotland (© JohnFScott/Getty Images)","copyrightlink":"https://www.bing.com/search?q=belted+galloway+cattle&form=hpcapt&filters=HpDate%3a%2220230419_1830%22","title":"Black-and-white bovines","quiz":"/search?q=Bing+homepage+quiz&filters=WQOskey:%22HPQuiz_20230419_BeltedGalloway%22&FORM=HPQUIZ","wp":true,"hsh":"fc6b9c083ac62ad2899429efd275c5fd","drk":1,"top":1,"bot":1,"hs":[]}],"tooltips":{"loading":"Loading...","previous":"Previous image","next":"Next image","walle":"This image is not available to download as wallpaper.","walls":"Download this image. Use of this image is restricted to wallpaper only."}}


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Tech-How** [comment]
Ok, thanks for that. Next, could you try in the shortcuts app, click on the three dots to open the shortcut code. Then click the play button so you can see each step as it's being executed. You might have to click on Refresh in the menu that comes up. Can you see which step it gets stuck on?

Also, which version of iOS are you using, and what device?

**Comment by YashPatel000** [comment]
I am currently on IOS 16.4.1 on iphone 14 pro.

It gets time out on 1st screenshot.

Then I tried and detete that command and other related to it then it gets time out on 2nd screenshot command.

I think its not getting the files from the links.

My internet is fines i also tried other bing wallpaper shortcut which works fine.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Tech-How** [comment]
Ok, could you tell me the name of the command that it times out on? Also, in the shortcut editor, there is a dictionary block near the top. Does removing the notifications value make a difference?

**Comment by YashPatel000** [comment]
Nope its not working,
Attached the image of the command (get content )that got time out.
I think the link is not working, tried opening the link in browser but it does not open


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Tech-How** [comment]
I just tested on my iPhone running iOS 16.4.1 and it was able to download the wallpaper. I'm afraid GitHub doesn't show email attachments here, do you mind uploading the screenshot to Imgur or a similar site and sharing the link here?

**Comment by YashPatel000** [comment]
Here is the link of the screenshot.
https://drive.google.com/file/d/18xKOghWA2fvVtujl5-NeFtH7pJSVZQOF/view?usp=drivesdk

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Tech-How** [comment]
Oh! That's an image that's supposed to be shown during the initial setup to explain how the automation works. You can delete that block and the one below it, and the rest of the shortcut should function as normal. Also, you'll probably need to press no thanks when asked to save the bing icon for use with the home screen, since it's loaded from the same server.

Just keep in mind that when creating the automation, add a text block with the number 0 right before the run shortcut command to tell it to skip the menu. Then click the down arrow on the run shortcut block, and make sure the text block is specified for the input command.

Hope this works! I'll have to investigate that and maybe host the image somewhere else.

**Comment by YashPatel000** [comment]
Yup,  deleted all the block with the github links and other related to it. Now it works fines and the automation too. Thanks for the shortcut✌️.

Also this block too get timeout.

https://drive.google.com/file/d/1RIuzii1mrt9eUD-5CZeWE2iW1UlNwPw_/view?usp=drivesdk



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Tech-How** [comment]
Glad it works now!
