### ISSUE TITLE
Any video tutorial

### ISSUE THREAD

**Issue by prabhashsatyarthi** [Tech-How/Bing-Wallpaper-for-iOS#12]
Hi there! I am unable to do the steps. May kindly show me how to do in video. Thank you.

**Comment by Tech-How** [comment]
Hi,
I've just made a video tutorial [here](https://raw.githubusercontent.com/Tech-How/Bing-Wallpaper-for-iOS/main/images/automation_tutorial.mp4). Apologies for the delay, hope this helps!
