### ISSUE TITLE
Shortcut runs but wallpaper doesn’t change

### ISSUE THREAD

**Issue by rdkgit** [Tech-How/Bing-Wallpaper-for-iOS#13]
Hi!

the shortcut runs each morning but doesn’t change the wallpaper.

i have to run it each morning by hand and select refresh wallpaper and it makes me choose an image.

how do i configure so it does this automatically?

thank you,

Bobby 
iPadOS 17.6.1

**Comment by Tech-How** [comment]
Hi Bobby,
I've just made a video tutorial as some people were confused with the steps. Please give it a look and let me know if it clears things up.
[Video](https://raw.githubusercontent.com/Tech-How/Bing-Wallpaper-for-iOS/main/images/automation_tutorial.mp4)

**Comment by rdkgit** [comment]
Thank you.  If I have it already installed, is it possible to go set the variable or is it easier to just uninstall and re-install?  Thanks.

**Comment by Tech-How** [comment]
The options can be changed again in the shortcut's options page, under Setup > Customize shortcut. The automation is independent from the shortcut, so you can create it without reinstalling.
![image](https://github.com/user-attachments/assets/d0d70d65-ef08-441d-a900-65b6c17214dd)

**Comment by rdkgit** [comment]
Man, this is funny.  Your screens bear no resemblance to what I'm looking at on my ipad.  And I'm a computer programmer.  Whoever designed this shortcut interface should be drawn and quartered.

**Comment by rdkgit** [comment]
I deleted my automation am adding a new one.  I never get the option of setting text=0 as an action.  Did I miss some other setup?  Thank you for all your help.

**Comment by Tech-How** [comment]
No problem, when you go to create a personal automation do you see a search box at the bottom that allows you to search for actions, like in the video? (It may be at the top left on an iPad?) There should be an action called "text", where you can input the number 0. Then, search for the action "Run shortcut", and select the Bing Wallpaper shortcut from the block when it is inserted into the automation. If you click the blue arrow to expand the "Run shortcut" action, you should see that the input is labeled as "text".

If you can share a screenshot or video of what you're seeing, it would be helpful.

**Comment by rdkgit** [comment]
Think I got it, thank you for all your help.  I'll know tomorrow after breakfast whether the 6am automation ran or not.

Edit: automation did not run this morning but I think its because I set "after confirmation".  Changed that.  Will check tomorrow.

**Comment by TSSimonSemmler** [comment]
Hi it looks like this für me, do you have any idea, on how to get the Text as Input? 
![IMG_5240](https://github.com/user-attachments/assets/eafef248-5344-422c-8df3-6306a3de0ecd)

Device: iPhone 12 Pro Max
iOS: 18.0.1

**Comment by Tech-How** [comment]
Hi, check out [this video](https://drive.google.com/file/d/1uGhSUjxWuSwuxt99o_jvXMZX_SZz9jHC/view). You should have a "Choose Variable" option next to the Input label. If you do not have that option, this could be a bug with iOS 18. I'd try fully restarting your phone first, and confirming on another phone, if you're able to.

(If anybody else is running into the same issue as TSSimon, _please_ comment below so I can confirm.)

**Comment by TSSimonSemmler** [comment]
Hi @Tech-How, thank you for this video. The "Choose Variable" option isn't visible for me on my iPhone and my iPad, so there seems to be a bug in iOS 18, which unfortunately a restart didn't fix. But then I have to wait and hope for a bug fix from Apple

**Comment by Tech-How** [comment]
Also for any curious minds stumbling across this thread, the reason it requires passing the number 0 in the automation is because I wanted a way for the user to be able to run the shortcut directly to access some additional features. When no input is passed, it pulls up a menu. When a number 0-7 is passed, it runs automatically and sets the wallpaper to that number index. 0 is today's wallpaper, 1 would set it to yesterday's, etc.

**Comment by rdkgit** [comment]
Woke up this morning and my ipad had successfully and automatically changed backgrounds.  Setting Text=0 did the trick as well as selecting "run immediately".  Thank you.

Closing now since I opened the issue.
