### ISSUE TITLE
iOS 18 Automation Bug ("Choose Variable") missing

### ISSUE THREAD

**Issue by Tech-How** [Tech-How/Bing-Wallpaper-for-iOS#14]
Hi @Tech-How, thank you for this video. The "Choose Variable" option isn't visible for me on my iPhone and my iPad, so there seems to be a bug in iOS 18, which unfortunately a restart didn't fix. But then I have to wait and hope for a bug fix from Apple

_Originally posted by @TSSimonSemmler in https://github.com/Tech-How/Bing-Wallpaper-for-iOS/issues/13#issuecomment-2416836777_

**Comment by TwoPlayer** [comment]
Is it maybe possible to get a version of this shortcut, wich always act like it was start with the variable 0? Or that there‘s a setting where you can enter the variable? Looking at Apples record it will probably take some time, before this Bug is fixed 😅

**Comment by TwoPlayer** [comment]
iOS 18.1 fixed the problem for me 👍🏻 Everything is working smoothly now
