### ISSUE TITLE
Where is the wallpaper stored without saving?

### ISSUE THREAD

**Issue by qaseem5** [Tech-How/Bing-Wallpaper-for-iOS#3]
In which location is the wallpaper stored if one does not safe it just for applying purpose, I don’t see it in the recent photos or anywhere?

**Comment by Tech-How** [comment]
Hi,
iOS stores the currently applied wallpaper internally in the file system. It's not accessible to the user or stored in a photo library, and will be overwritten when the wallpaper is changed. As far as I know there isn't a way to access it without jailbreaking the device and installing a third-party file manager.

**Comment by qaseem5** [comment]
Okay Thank you
