### ISSUE TITLE
no text option in automation

### ISSUE THREAD

**Issue by gherbetto** [Tech-How/Bing-Wallpaper-for-iOS#4]
Love your work! I only have one issue that when creating an automation there is no text option in the list. 
And without it my shortcut runs with menu queries. Could you assist me in finding this option, to get it to work. Please?

**Comment by Tech-How** [comment]
Hi and thank you! That's strange there is no text option. Maybe with localization or language differences it could be called something else? If it's not available, try searching for the number action, and enter the number zero in there above the run shortcut action.

Make sure that the little dropdown arrow in the run shortcut action is linked to the number action.
Let me know how it goes.

**Comment by gherbetto** [comment]
Wow thanks, that did work!
It's called a Number action
iOS 17.1.1 iPhone 11
