### ISSUE TITLE
Automatic picture update

### ISSUE THREAD

**Issue by Aleksandr-Buksa** [Tech-How/Bing-Wallpaper-for-iOS#6]
Hello! Is it possible to set up automatic wallpaper updating without user interaction after the banner appears?

**Comment by Tech-How** [comment]
Hi there, if the automation is set up correctly according to the instructions here, the wallpaper should change automatically at the time you specify. If a banner is appearing requesting user interaction, it's possible you forgot to add a text or number block containing the number "0" before the run shortcut action in the automation. Could you confirm what type of banner you're seeing and what your automation looks like?

**Comment by Aleksandr-Buksa** [comment]
Да, я не добавил текстовый блок и 0. Сейчас я это исправил, и обои сменились автоматически. Я прикрепляю фото автоматизации и хотел бы узнать все ли верно я сделал.
![IMG_2822](https://github.com/Tech-How/Bing-Wallpaper-for-iOS/assets/106695741/3f2ffe41-7353-404c-9c4b-1d150eb6bd0e)

**Comment by Tech-How** [comment]
Yes, it looks good!

**Comment by Aleksandr-Buksa** [comment]
Should the block highlighted with a red line appear at the end of the automation?
![IMG_2822](https://github.com/Tech-How/Bing-Wallpaper-for-iOS/assets/106695741/b96746d7-77ae-4c64-8390-f018f9620bed)

**Comment by Tech-How** [comment]
Yes, that is leftover code from the initial setup. It doesn't do anything.

**Comment by Aleksandr-Buksa** [comment]
Great! Thanks for your time and help!
