### ISSUE TITLE
It doesn't work as of today 

### ISSUE THREAD

**Issue by qabRieL99** [Tech-How/Bing-Wallpaper-for-iOS#8]
It shows an error about not being able to convert data types. 
![IMG_3328](https://github.com/Tech-How/Bing-Wallpaper-for-iOS/assets/64584999/bd838fae-4123-4d67-89c4-ed6b8c3fb505)

**Comment by Tech-How** [comment]
Hello,
Thanks for pointing it out. It looks like Bing changed something with their API, I'll be investigating shortly and will reply back with any new information.

**Comment by Tech-How** [comment]
Edit:
Turns out Bing May just be experiencing server issues. It should work again tomorrow.

https://downdetector.com/status/bing/

**Comment by Tech-How** [comment]
Functional as of 5/24/24
